In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from tensorflow import keras

In [2]:
df = pd.read_csv("./BPM_values.csv")
df.head()

State  BPM  gender  age                bred
0  Anomaly   60    male    5     German Shepherd
1  Anomaly   61    male    3             Bulldog
2  Anomaly   62  female    4  Labrador Retriever
3  Anomaly   63  female    5    Golden Retriever
4  Anomaly   64    male    2  Labrador Retriever

In [3]:
df['State'].value_counts()

State
Normal     56
Anomaly    55
Name: count, dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   State   111 non-null    object
 1   BPM     111 non-null    int64 
 2   gender  111 non-null    object
 3   age     111 non-null    int64 
 4   bred    111 non-null    object
dtypes: int64(2), object(3)
memory usage: 4.5+ KB


In [5]:
df.isnull().sum()

State     0
BPM       0
gender    0
age       0
bred      0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])
df['bred'] = le.fit_transform(df['bred'])
df['State'] = le.fit_transform(df['State'])
df.head()

State  BPM  gender  age  bred
0      0   60       1    5     3
1      0   61       1    3     1
2      0   62       0    4     5
3      0   63       0    5     4
4      0   64       1    2     5

In [8]:
state_name = le.classes_
print(state_name)

['Anomaly' 'Normal']


In [9]:
X = df.drop(columns=['State'])
y = df['State']
X.head(3)

BPM  gender  age  bred
0   60       1    5     3
1   61       1    3     1
2   62       0    4     5

In [10]:
y.head(3)

0    0
1    0
2    0
Name: State, dtype: int32

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=69)

In [12]:
x_test

BPM  gender  age  bred
8     68       0    3     1
13    73       1    1     3
66   106       1    5     4
17    77       0    3     5
64   104       1    3     3
81   121       1    5     3
52    92       1    2     5
33    83       0    3     4
10    70       1    5     6
91   131       0    2     1
98   138       1    4     6
71   111       0    1     0
84   124       1    1     1
34    83       1    4     1
62   102       0    4     0
30    82       1    4     5
26    80       0    5     1
102  142       1    1     0
28    80       1    2     3
87   127       1    3     5
51    92       0    5     4
31    82       1    1     3
68   108       0    2     4
94   134       0    1     5
100  140       0    1     2
104  144       1    3     3
42    86       1    5     1
15    75       0    1     3
25    80       1    5     6
5     65       0    3     3
36    84       1    2     6
92   132       1    1     5
58    98       1    5     6
6     66       1    1     1

In [13]:
x_train.shape

(77, 4)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
print(x_train[:1])
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train[:1])
print(x_test[:1])

    BPM  gender  age  bred
95  135       0    3     3
[[ 1.30803397 -0.91287093 -0.3825599   0.13083893]]
[[-1.33105373 -0.91287093 -0.3825599  -1.05440782]]


In [15]:
y_train = keras.utils.to_categorical(y_train, num_classes=2)
print(y_train[:5])

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [16]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [17]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(x_train.shape[-1], )))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(units=2, activation='softmax'))

In [18]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 1282 (5.01 KB)
Trainable params: 1282 (5.01 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.fit(x_train, y_train, epochs=100, verbose=2)

Epoch 1/100
3/3 - 0s - loss: 0.7736 - accuracy: 0.4675 - 482ms/epoch - 161ms/step
Epoch 2/100
3/3 - 0s - loss: 0.7264 - accuracy: 0.5455 - 5ms/epoch - 2ms/step
Epoch 3/100
3/3 - 0s - loss: 0.7333 - accuracy: 0.4805 - 4ms/epoch - 1ms/step
Epoch 4/100
3/3 - 0s - loss: 0.7530 - accuracy: 0.4805 - 4ms/epoch - 1ms/step
Epoch 5/100
3/3 - 0s - loss: 0.7136 - accuracy: 0.5584 - 4ms/epoch - 1ms/step
Epoch 6/100
3/3 - 0s - loss: 0.7009 - accuracy: 0.5584 - 4ms/epoch - 1ms/step
Epoch 7/100
3/3 - 0s - loss: 0.6703 - accuracy: 0.6104 - 4ms/epoch - 1ms/step
Epoch 8/100
3/3 - 0s - loss: 0.6680 - accuracy: 0.6234 - 4ms/epoch - 1ms/step
Epoch 9/100
3/3 - 0s - loss: 0.6625 - accuracy: 0.6104 - 4ms/epoch - 1ms/step
Epoch 10/100
3/3 - 0s - loss: 0.6269 - accuracy: 0.7013 - 5ms/epoch - 2ms/step
Epoch 11/100
3/3 - 0s - loss: 0.6526 - accuracy: 0.5974 - 4ms/epoch - 1ms/step
Epoch 12/100
3/3 - 0s - loss: 0.6227 - accuracy: 0.7143 - 4ms/epoch - 1ms/step
Epoch 13/100
3/3 - 0s - loss: 0.5828 - accuracy: 0.7273 -

In [20]:
x_test

array([[-1.33105373, -0.91287093, -0.3825599 , -1.05440782],
       [-1.13410689,  1.09544512, -1.81949223,  0.13083893],
       [ 0.16574228,  1.09544512,  1.05437242,  0.7234623 ],
       [-0.97654941, -0.91287093, -0.3825599 ,  1.31608568],
       [ 0.08696354,  1.09544512, -0.3825599 ,  0.13083893],
       [ 0.75658281,  1.09544512,  1.05437242,  0.13083893],
       [-0.38570888,  1.09544512, -1.10102607,  1.31608568],
       [-0.7402132 , -0.91287093, -0.3825599 ,  0.7234623 ],
       [-1.252275  ,  1.09544512,  1.05437242,  1.90870905],
       [ 1.1504765 , -0.91287093, -1.10102607, -1.05440782],
       [ 1.42620208,  1.09544512,  0.33590626,  1.90870905],
       [ 0.36268912, -0.91287093, -1.81949223, -1.6470312 ],
       [ 0.87475092,  1.09544512, -1.81949223, -1.05440782],
       [-0.7402132 ,  1.09544512,  0.33590626, -1.05440782],
       [ 0.0081848 , -0.91287093,  0.33590626, -1.6470312 ],
       [-0.77960257,  1.09544512,  0.33590626,  1.31608568],
       [-0.85838131, -0.

In [21]:
prediction = model.predict(x_test)

2/2 [==============================] - 0s 2ms/step


In [22]:
import numpy
numpy.array(x_test[0])

array([-1.33105373, -0.91287093, -0.3825599 , -1.05440782])

In [23]:
model.save('heart_anomaly_model.h5', model)

c:\Users\ashen\anaconda3\envs\detection\lib\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [24]:
prediction = model.predict(x_test)
print(prediction[:10])
prediction = np.argmax(prediction, axis=-1)
print(state_name[prediction[:1][0]])

2/2 [==============================] - 0s 1ms/step
[[0.03409904 0.9659009 ]
 [0.08927129 0.9107287 ]
 [0.82895845 0.17104155]
 [0.4726813  0.5273187 ]
 [0.7088712  0.2911288 ]
 [0.988447   0.01155299]
 [0.2223389  0.77766114]
 [0.29892337 0.7010766 ]
 [0.4756961  0.5243039 ]
 [0.9916997  0.0083003 ]]
Normal


In [25]:
prediction = np.argmax(prediction, axis=-1)
print(state_name[prediction])

Anomaly


In [34]:
from tensorflow.keras.models import load_model
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
le = LabelEncoder()
sc = StandardScaler()

df = pd.read_csv("./BPM_values.csv")

df['gender'] = le.fit_transform(df['gender'])
df['bred'] = le.fit_transform(df['bred'])
df['State'] = le.fit_transform(df['State'])
state_name = le.classes_
X = df.drop(columns=['State'])
y = df['State']
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=69)
input = [60, "female", 5, "German Shepherd"]

# Create mapping dictionaries
gender_map = {"female": 0, "male": 1}
breed_map = {"German Shepherd": 0, "Bulldog": 1, "Labrador Retriever": 2, "Golden Retriever": 3}
# X_new = np.array([[60 , 1, 5, 1 ]])
# Apply mappings
input[1] = gender_map[input[1]]
input[3] = breed_map[input[3]]

print(input)
X_new = np.array([input])
x_train = sc.fit_transform(x_train)
x_test = sc.transform(X_new)

# x_test = sc.transform(x_test)
model = load_model('heart_anomaly_model.h5')
prediction = model.predict(x_test)
print(prediction[:10])
prediction = np.argmax(prediction, axis=-1)
print(state_name[prediction][0])

[60, 0, 5, 0]
1/1 [==============================] - 0s 39ms/step
[[0.01223083 0.9877692 ]]
Normal


C:\Users\ashen\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
